### ISSUE TITLE
The integration makes a sensor entity for one account but not the other

### ISSUE THREAD

**Issue by Aasikki** [jesmak/matkahuolto_tracking#1]
Hey I have a small issue with this integration, when I configure it with my matkahuolto account, I get no tracking entity at all, but with my girlfriends account it works flawlessly. I wonder what's the issue?

I found this in my home assistant core logs:
```
Logger: homeassistant.components.sensor
Source: custom_components/matkahuolto_tracking/sensor.py:140
Integration: Sensor (documentation, issues)
First occurred: 12:14:36 (2 occurrences)
Last logged: 12:14:59

matkahuolto_tracking: Error on device update!
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 507, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 732, in async_device_update
    await task
  File "/config/custom_components/matkahuolto_tracking/sensor.py", line 140, in async_update
    latest_timestamp = shipment["lastEvent"]["time"] if latest_timestamp is None or shipment[
KeyError: 'lastEvent'
```

**Comment by jesmak** [comment]
Hey. Thanks for reporting this. Based on the stack trace, it seems one or more shipments received from Matkahuolto's API are missing the lastEvent property completely. I'll modify the sensor so that such shipments are ignored completely. It's hard to say what exactly is different with these shipments, but if there's no information about the latest event, I think it's safe to assume it can be ignored. 

If you're willing to do some debugging to check what is special with that one shipment, I can give some guidance on how to do that. I'll anyway ignore these kinds of shipments for now.

**Comment by Aasikki** [comment]
> Hey. Thanks for reporting this. Based on the stack trace, it seems one or more shipments received from Matkahuolto's API are missing the lastEvent property completely. I'll modify the sensor so that such shipments are ignored completely. It's hard to say what exactly is different with these shipments, but if there's no information about the latest event, I think it's safe to assume it can be ignored.
> 
> If you're willing to do some debugging to check what is special with that one shipment, I can give some guidance on how to do that. I'll anyway ignore these kinds of shipments for now.

Sounds good to me! Happy to do some debugging if you can guide me.

Also kinda funny, I noticed you also have a magic mirror module for this, but I switched to home assistant Lovelace dash for my magic mirror so I'm using this on on it instead haha! And by the way Finnish (too?) but I guess it's best to keep the conversation in English so other can understand it too.

**Comment by jesmak** [comment]
> Sounds good to me! Happy to do some debugging if you can guide me.
> 
> Also kinda funny, I noticed you also have a magic mirror module for this, but I switched to home assistant Lovelace dash for my magic mirror so I'm using this on on it instead haha! And by the way Finnish (too?) but I guess it's best to keep the conversation in English so other can understand it too.

There's now a new release (v1.0.0-beta3) that should fix the crash. Can you try it out to see if it helps? Yes, I originally made this for Magic Mirror, but then I too switched to Home Assistant so the Magic Mirror module is no longer maintained. Finnish is my main language but yes, better keep this in English in case there are English speakers out there using this module. I will put some debugging instructions to another comment.

Edit: You don't have to update everything to test the fix. You can just download sensor.py and replace the one you have with this latest version, to test this fix. Have to restart Home Assistant though after replacing the file.

**Comment by jesmak** [comment]
Here's some debugging instructions. Sorry, I have no idea how proficient you are with these kinds of things so I'll try to be thorough. These instructions are for Google Chrome but should be somewhat similar with other browsers too.

First, open matkahuolto.fi in your browser and then open developer console (press F12 on Chrome). 

![image](https://user-images.githubusercontent.com/54674286/229588470-51a17d23-f27e-4de1-9a87-f9576f2e97b1.png)

Select network tab on the developer console, enter "received" to filter input and log in with your Matkahuolto-account. A few lines should appear. The one we are interested in is the row with status 200. 

![image](https://user-images.githubusercontent.com/54674286/229588764-84746565-9774-41a0-97e9-6507e32a640d.png)

Click on that row and select Response tab. You should see all the shipments here that Matkahuolto's API is returning. Copy the contents to some text editor and try to find the shipment that contains no lastEvent property.

![image](https://user-images.githubusercontent.com/54674286/229589066-457e29ff-d4a7-49b6-9956-a2ef2e55b0e3.png)

Normal shipments should have a lastEvent-property like the one above, but for some reason your account's shipment list contains something that does not have this info. I'd like to know if it's even a shipment or something completely different. If it's not a shipment, then my fix that ignores these is just fine. If it's an actual shipment that should be shown, then I would need a bit more help in figuring out what is happening here.

**Comment by Aasikki** [comment]
> > Sounds good to me! Happy to do some debugging if you can guide me.
> > Also kinda funny, I noticed you also have a magic mirror module for this, but I switched to home assistant Lovelace dash for my magic mirror so I'm using this on on it instead haha! And by the way Finnish (too?) but I guess it's best to keep the conversation in English so other can understand it too.
> 
> There's now a new release (v1.0.0-beta3) that should fix the crash. Can you try it out to see if it helps? Yes, I originally made this for Magic Mirror, but then I too switched to Home Assistant so the Magic Mirror module is no longer maintained. Finnish is my main language but yes, better keep this in English in case there are English speakers out there using this module. I will put some debugging instructions to another comment.
> 
> Edit: You don't have to update everything to test the fix. You can just download sensor.py and replace the one you have with this latest version, to test this fix. Have to restart Home Assistant though after replacing the file.

Thanks for the instructions, I'll check it tomorrow. I suspect it may really be something other than a shipment though, as I believe didn't have any on my list at one point, yet the integration still crashed.

Edit: updated the integration using my phone (I reinstalled it through hacs a couple days ago as I noticed the existence of hacs.json) and it now seems to works perfectly!

**Comment by Aasikki** [comment]
Looks like I found a some shipments that are missing the lastEvent property. There actually were quite a few, and most of them have in common that they are shipments that are actually archived, except one which was delivered yesterday and isn't archived yet. My gf's account probably didn't have this issue as she hasn't archived any shipments. So I quess the fix you have done is mostly fine, as archived shipments definitely don't need to be displayed in home assistant. But then again maybe showing ones that are delivered but not archived could be useful, at least for maybe couple days after delivery?

This is the sipment that was delivered yesterday:
```
{
    
// REDACTED
// ...
    
    "destinationPlaceWoltVenueId": null,
    "agreedDeliveryStartTime": null,
    "agreedDeliveryEndTime": null,
    "sizeCode": null,
    "shipmentWeight": 0.1,
    "shipmentVolume": 0.001,
    "parcelCount": 1,
    "deliveryTimeToken": null,
    "parcels": [
        {
            "parcelNumber": "REDACTED",
            "weight": 0.1,
            "length": 18,
            "width": 11,
            "height": 6,
            "volume": 0.001,
            "shelveCode": "REDACTED",
            "dangerousGoods": false,
            "limitedQuantities": false
        }
    ],
    "additionalServices": [],
    "productCode": "80",
    "shippingWeight": 1,
    "transferToDelivery": false,
    "transferToPickupPoint": false,
    "postponeReturn": false,
    "senderId": null,
    "receiverId": null,
    "customerReturnUntil": null,
    "returnPermissionCode": null,
    "deliveryPinCode": "REDACTED",
    "customsStatus": "CLEARED",
    "originalShipmentNumber": null,
    "returnShipmentNumber": null,
    "unsuccessfulDelivery": false,
    "pickupFromTerminal": true,
    "deliveryIncluded": false,
    "readyForCollect": false,
    "waitingUser": false,
    "deliveryAgreed": false,
    "status": "delivered",
    "direction": "received"
},
```
  <br>

And this is one of the archived ones:
```
{
    
// REDACTED
// ...

    "destinationPlaceWoltVenueId": null,
    "agreedDeliveryStartTime": null,
    "agreedDeliveryEndTime": null,
    "sizeCode": null,
    "shipmentWeight": 0.1,
    "shipmentVolume": 0.003,
    "parcelCount": 1,
    "deliveryTimeToken": null,
    "parcels": [
        {
            "parcelNumber": "REDACTED",
            "weight": 0.14,
            "length": 28,
            "width": 21,
            "height": 5,
            "volume": 0.003,
            "shelveCode": "REDACTED",
            "dangerousGoods": false,
            "limitedQuantities": false
        }
    ],
    "additionalServices": [],
    "productCode": "80",
    "shippingWeight": 1,
    "transferToDelivery": false,
    "transferToPickupPoint": false,
    "postponeReturn": false,
    "senderId": null,
    "receiverId": null,
    "customerReturnUntil": null,
    "returnPermissionCode": null,
    "deliveryPinCode": "REDACTED",
    "customsStatus": "CLEARED",
    "originalShipmentNumber": null,
    "returnShipmentNumber": null,
    "unsuccessfulDelivery": false,
    "pickupFromTerminal": true,
    "deliveryIncluded": false,
    "readyForCollect": false,
    "waitingUser": false,
    "deliveryAgreed": false,
    "status": "delivered",
    "direction": "received"
},
```

**Comment by jesmak** [comment]
This is a bit weird. I have many delivered shipments on my account and all of them have a lastEvent-property, and the idea really is to show these packages too. End users can define in the module's integration settings in HASS for how long delivered packages are shown. Technically I can make do without the lastEvent-property. That data (for delivered packages at least) is available elsewhere in the dataset too. One issue though is the archived state. Comparing the two jsons you sent shows virtually no differences. 

Can you check once more if there's something in the redacted data that would indicate a shipment has been archived? If there is nothing to indicate that, I basically have to show archived shipments too. Not a huge issue as the end users can still configure for how long delivered packages are shown, and shipments are sorted based on event timestamps. But like you said, it would make sense to hide archived shipments.

**Comment by Aasikki** [comment]
> This is a bit weird. I have many delivered shipments on my account and all of them have a lastEvent-property, and the idea really is to show these packages too. End users can define in the module's integration settings in HASS for how long delivered packages are shown. Technically I can make do without the lastEvent-property. That data (for delivered packages at least) is available elsewhere in the dataset too. One issue though is the archived state. Comparing the two jsons you sent shows virtually no differences.
> 
> Can you check once more if there's something in the redacted data that would indicate a shipment has been archived? If there is nothing to indicate that, I basically have to show archived shipments too. Not a huge issue as the end users can still configure for how long delivered packages are shown, and shipments are sorted based on event timestamps. But like you said, it would make sense to hide archived shipments.

Weird indeed, the only thing I can see it that the archived ones all have "shipmentStatus": "60", but that's also true for the one that's delivered but not archived. I also tried to archive one that wasn't delivered but the shipment status didn't change to 60 for that, so it must just mean that it's delivered. I also tried to archive and unarchive a shipment to see if anything changes but the response it exactly the same archived or not.

**Comment by jesmak** [comment]
Thanks for the added details. I've just published a new version (1.0.0-beta4) that fixes this issue. It will now properly show those shipments that don't have lastEvent-properties too. Unfortunately, for reasons described in your previous message, archived shipments will also be shown. I will now close this issue. Feel free to open another one if you stumble into any other problems.

Edit: Took this out of pre-release so the latest version is now just 1.0.0
